### ISSUE TITLE
create uf2 file with configuration

### ISSUE THREAD

**Issue by bobricius** [kermite-org/Kermite#13]
Hi, is there any way how to create uf2 firmware + configuration for Raspberry pi PICO?

If I good understand I need At first write firmware, then save configuration from web app or?

Thanks, it is amazing project

**Comment by yahiro07** [comment]
Hi.
I'm assuming you want to write initial keymapping into generated uf2, right?

The firmware peripheral configurations (like board pin assigns for key matrix , LED setup, ...etc) are injected into the generated uf2 binary during the firmware setup wizard.

However, The key mappings are separated from the firmware binary and it is supposed to be uploaded only from the Web GUI.

So unfortunately you cannot create uf2 binary with embedded keymapping.

**Comment by bobricius** [comment]
Thanks, how to download this file, I can not found  in menu

**Comment by yahiro07** [comment]
![Screenshot_20240310_030324](https://github.com/kermite-org/Kermite/assets/321700/74a91e3f-8ad6-4bfc-b6e2-5ffb1ae4b882)

Did you see the project quick setup wizard?
There is 'download uf2 file' button at the step 2 in the wizard.
