### ISSUE TITLE
One press send multiple characters

### ISSUE THREAD

**Issue by bobricius** [kermite-org/Kermite#15]
I am very often get twice characters, ... insstead a I get aa ... double spaces ....
I  have Kailh Low profile Choc switches and Rpi PICO

I try adjust repeat delaay in os but not heelp
testeed on win and mac, same issuee

Is somewhere debounce Debounce adjust ?

**Comment by yahiro07** [comment]
Hi, currently there are no mechanism to reduce key chattering.
I'd like to implement configurable deboucing delay logic to avoid chatterings.

**Comment by yahiro07** [comment]
![Screenshot_20240311_005029](https://github.com/kermite-org/Kermite/assets/321700/c7ad3603-eb99-40a4-ab13-c3766b2ff088)

I've implemented debouncing filter that reduces chattering.
There is a Debouncing Wait parameter in the Custom Parameters section.
Here, you can specify a wait time value between 0ms and 200ms.
Typically, if you have chatterings, the weight time value of 10-50ms are enough for this.
